############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport
import time


class shock_util(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login',
            service_ver='release',
            async_job_check_time_ms=5000):
        if url is None:
            url = 'https://kbase.us/services/njs_wrapper'
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            async_job_check_time_ms=async_job_check_time_ms)

    def _check_job(self, job_id):
        return self._client._check_job('shock_util', job_id)

    def _node_to_file_submit(self, params, context=None):
        return self._client._submit_job(
             'shock_util.node_to_file', [params],
             self._service_ver, context)

    def node_to_file(self, params, context=None):
        """
        :param params: instance of type "NodeToFileParams" -> structure:
           parameter "shock_id" of String, parameter "file_path" of String
        :returns: instance of type "NodeToFileOutput" -> structure: parameter
           "node_file_name" of String, parameter "attributes" of mapping from
           String to String
        """
        job_id = self._node_to_file_submit(params, context)
        while True:
            time.sleep(self._client.async_job_check_time)
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]

    def _file_to_node_submit(self, params, context=None):
        return self._client._submit_job(
             'shock_util.file_to_node', [params],
             self._service_ver, context)

    def file_to_node(self, params, context=None):
        """
        :param params: instance of type "FileToNodeParams" -> structure:
           parameter "file_path" of String, parameter "attributes" of mapping
           from String to String
        :returns: instance of type "FileToNodeOutput" -> structure: parameter
           "shock_id" of String
        """
        job_id = self._file_to_node_submit(params, context)
        while True:
            time.sleep(self._client.async_job_check_time)
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]

    def status(self, context=None):
        job_id = self._client._submit_job('shock_util.status', 
            [], self._service_ver, context)
        while True:
            time.sleep(self._client.async_job_check_time)
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]
